### ISSUE TITLE
Error after fresh install YNH 

### ISSUE THREAD

**Issue by anivard** [YunoHost-Apps/invoiceninja_ynh#20] opened 2021-01-03 17:53 UTC
Hello,

I done a fresh install today of YNH and try InvoiceNinja.
After the assistante, the URL :
`Error: app is already configured, backup then delete the .env file to re-run the setup`

The file /var/www/invoiceninja/.env is ok : 
`
APP_ENV=production
APP_DEBUG=false
APP_LOCALE=fr
`

**MariaDB access is ok** but the user table is empty.
`
MariaDB [invoiceninja]> select * from users;
Empty set (0.002 sec)

MariaDB [invoiceninja]> select * from user_accounts;
Empty set (0.003 sec)
`

**php -v**
`
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
`

I tried to reset the .env and re-run setup, nothing change.
Which logs file I should look at nginx, php, bootstrap?

Thanks,

**Comment by rndmh3ro** [comment] 2021-01-03 18:22
This seems to be a bug with invoiceninja itself: https://github.com/invoiceninja/dockerfiles/issues/238

**Comment by anivard** [comment] 2021-01-03 19:00
Ok, so how I use `image: invoiceninja/invoiceninja:alpine-4.5.18` ?
There are no docker on YNH ?

So, I should the testing tree ?
`yunohost app install https://github.com/YunoHost-Apps/invoiceninja_ynh/tree/testing --debug`

**Comment by rndmh3ro** [comment] 2021-01-03 19:08
> Ok, so how I use image: invoiceninja/invoiceninja:alpine-4.5.18 ?
> There are no docker on YNH ?

You can't - it has nothing to do with docker since it happens regardless where you run IN.

>So, I should the testing tree ?

Testing has the same version as master. I'll need to rollback master.

**Comment by rndmh3ro** [comment] 2021-01-03 19:40
I updated the master branch to use the old version. Can you please try again?

**Comment by anivard** [comment] 2021-01-03 19:59
Same issue

**Comment by verzog** [comment] 2021-01-04 07:26
Same issue also - TIA

**Comment by anivard** [comment] 2021-01-04 21:13
Hello,

I done a "bad" way with : 
1. move old directory (YNH package)
2. download zip
3. install composer (apt)
4. composer install

And after setup... => the user was created (not done with YNH package)
Test: Ok

A reswap directory (prod YNH package)
Test: ok

**Comment by rndmh3ro** [comment] 2021-01-05 05:50
> And after setup... => the user was created (not done with YNH package)

What user do you mean?

**Comment by anivard** [comment] 2021-01-05 06:56
When I deployed the IN package for YNH, the user table is empty.

MariaDB access is ok but the user table is empty.
`
MariaDB [invoiceninja]> select * from users;
Empty set (0.002 sec)

MariaDB [invoiceninja]> select * from user_accounts;
Empty set (0.003 sec)

**Comment by rndmh3ro** [comment] 2021-01-05 07:22
Ah yes. That's because the setup never ran, so the tables don't get created.

**Comment by starlord-a** [comment] 2021-01-16 00:51
Has this been fixed or are we still required to use @anivard (s) janky work around?

**Comment by delellis** [comment] 2021-03-17 10:31
InvoiceNinja setup is not working on Yunohost. 
An alternative would be **Akaunting**. 
Just saying.

**Comment by rndmh3ro** [comment] 2021-03-17 11:10
Does akaunting work on yunohost? Or this this just an ad?

**Comment by alexAubin** [comment] 2021-03-17 13:32
Sounds like just an ad

**Comment by jnrmy** [comment] 2021-03-25 16:12
Having the same issue. Is there a fix now ?

**Comment by rndmh3ro** [comment] 2021-03-25 16:28
No fix, yet. However I welcome any help.

**Comment by rndmh3ro** [comment] 2021-03-26 09:16
So this is definetly a regression with invoiceninja itself.

Installing v4.5.18 works. The latest version v4.5.35 doesn't.

As I have not much time to further debug this, I updated the code to use the old version.

**Comment by rndmh3ro** [comment] 2022-09-06 06:58
We just merged a new version where this should not happen anymore.

If it still does, please open a new issue for that, thanks,

**Closed by rndmh3ro** 2022-09-06 06:58 UTC
